version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    # volumes:
    #   - ./.env:/go/src/app/.env
    restart: always
    networks:
      - network-basic
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=aaaa
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=aaaa
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network-basic
    ports:
      - 5432:5432

networks:
  network-basic:
volumes:
  db: